using AutoMapper;
using FS.TimeTracking.Abstractions.DTOs.MasterData;
using FS.TimeTracking.Abstractions.DTOs.TimeTracking;
using FS.TimeTracking.Abstractions.Models.Application.MasterData;
using FS.TimeTracking.Abstractions.Models.Application.TimeTracking;
using FS.TimeTracking.Shared.DTOs.Report;
using System;
using System.Collections.Generic;

namespace FS.TimeTracking.Application.AutoMapper;

/// <summary>
/// Configuration profile for auto mapper.
/// </summary>
/// <seealso cref="Profile" />
public class TimeTrackingAutoMapper : Profile
{
    /// <summary>
    /// Initializes a new instance of the <see cref="TimeTrackingAutoMapper"/> class.
    /// </summary>
    /// <autogeneratedoc />
    public TimeTrackingAutoMapper()
    {
        ClearPrefixes();

        CreateMap<string, string>()
            .ConvertUsing(x => string.IsNullOrEmpty(x) ? null : x);

        CreateMap<List<Setting>, SettingDto>()
            .ConvertUsing<SettingsDtoConverter>();

        CreateMap<SettingDto, List<Setting>>()
            .ConvertUsing<SettingsFromDtoMapper>();

        CreateMap<Holiday, HolidayDto>()
            .ReverseMap()
            .ForMember(x => x.StartDate, x => x.ConvertUsing<TruncateToDayConverter, DateTimeOffset>())
            .ForMember(x => x.EndDate, x => x.ConvertUsing<TruncateToDayConverter, DateTimeOffset>())
            .ForMember(x => x.StartDateOffset, x => x.Ignore())
            .ForMember(x => x.EndDateOffset, x => x.Ignore());

        CreateMap<Customer, CustomerDto>()
            .ReverseMap();

        CreateMap<Project, ProjectDto>()
            .ReverseMap();

        CreateMap<Activity, ActivityDto>()
            .ReverseMap();

        CreateMap<Order, OrderDto>()
            .ReverseMap()
            .ForMember(x => x.StartDate, x => x.ConvertUsing<TruncateToDayConverter, DateTimeOffset>())
            .ForMember(x => x.DueDate, x => x.ConvertUsing<TruncateToDayConverter, DateTimeOffset>())
            .ForMember(x => x.StartDateOffset, x => x.Ignore())
            .ForMember(x => x.DueDateOffset, x => x.Ignore());

        CreateMap<TimeSheet, TimeSheetDto>()
            .ReverseMap()
            .ForMember(x => x.StartDate, x => x.ConvertUsing<TruncateToMinuteConverter, DateTimeOffset>())
            .ForMember(x => x.EndDate, x => x.ConvertUsing<TruncateNullableToMinuteConverter, DateTimeOffset?>())
            .ForMember(x => x.StartDateOffset, x => x.Ignore())
            .ForMember(x => x.EndDateOffset, x => x.Ignore());

        CreateMap<Holiday, HolidayGridDto>();

        CreateMap<Customer, CustomerGridDto>();

        CreateMap<Project, ProjectGridDto>();

        CreateMap<Activity, ActivityGridDto>()
            .ForMember(x => x.CustomerTitle, x => x.MapFrom(activity => activity.Project.Customer.Title));

        CreateMap<Order, OrderGridDto>();

        CreateMap<TimeSheet, TimeSheetGridDto>()
            .ForMember(x => x.CustomerTitle, x => x.MapFrom(timeSheet => timeSheet.Project.Customer.Title))
            .ForMember(x => x.Duration, x => x.MapFrom(timeSheet => timeSheet.EndDate - timeSheet.StartDate));

        CreateMap<TimeSheet, TimeSheetReportGridDto>()
            .ForMember(x => x.CustomerTitle, x => x.MapFrom(timeSheet => timeSheet.Project.Customer.Title))
            .ForMember(x => x.CustomerCompanyName, x => x.MapFrom(timeSheet => timeSheet.Project.Customer.CompanyName))
            .ForMember(x => x.CustomerDepartment, x => x.MapFrom(timeSheet => timeSheet.Project.Customer.Department))
            .ForMember(x => x.CustomerContactName, x => x.MapFrom(timeSheet => timeSheet.Project.Customer.ContactName))
            .ForMember(x => x.Duration, x => x.MapFrom(timeSheet => timeSheet.EndDate - timeSheet.StartDate));
    }
}
