using FS.TimeTracking.Shared.Models.Repository;
using System.Data.Common;

namespace FS.TimeTracking.Shared.Interfaces.Services
{
    /// <summary>
    /// Database specific exception handling
    /// </summary>
    /// <autogeneratedoc />
    public interface IDbExceptionService
    {
        /// <summary>
        /// Translates the database specific exception to an unified error code.
        /// </summary>
        /// <param name="dbException">The database exception.</param>
        DatabaseErrorCode TranslateDbException(DbException dbException);
    }
}