using FS.TimeTracking.Shared.Interfaces.Application.Services;
using System;

namespace FS.TimeTracking.Shared.DTOs.TimeTracking
{
    /// <summary>
    /// Non-generic factory for <see cref="TypeaheadDto{TValue}"/>.
    /// </summary>
    public class TypeaheadDto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TypeaheadDto{TValue}"/> class.
        /// </summary>
        /// <typeparam name="TValue">The type of the value.</typeparam>
        /// <param name="id">The value to be selected.</param>
        /// <param name="value">The label to display.</param>
        /// <param name="hidden"><c>true</c>, if the value is hidden; otherwise false.</param>
        public static TypeaheadDto<TValue> Create<TValue>(Guid id, TValue value, bool hidden)
            => new TypeaheadDto<TValue>(id, value, hidden);
    }

    /// <summary>
    /// Generic DTO returned by <see cref="ITypeaheadService"/>.
    /// </summary>
    /// <typeparam name="TValue">The type of the value.</typeparam>
    public class TypeaheadDto<TValue>
    {
        /// <summary>
        /// Gets or sets the value to be selected.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the label to display.
        /// </summary>
        public TValue Value { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="TypeaheadDto{TValue}"/> is hidden.
        /// </summary>
        /// <autogeneratedoc />
        public bool Hidden { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="TypeaheadDto{TValue}"/> class.
        /// </summary>
        /// <autogeneratedoc />
        public TypeaheadDto() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="TypeaheadDto{TValue}" /> class.
        /// </summary>
        /// <param name="id">The value to be selected.</param>
        /// <param name="value">The label to display.</param>
        /// <param name="hidden"><c>true</c>, if the value is hidden; otherwise false.</param>
        public TypeaheadDto(Guid id, TValue value, bool hidden)
            => (Id, Value, Hidden) = (id, value, hidden);
    }
}
