using FS.TimeTracking.Shared.Models.Configuration;
using FS.TimeTracking.Shared.Models.TimeTracking;
using LinqToDB.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.Logging;
using System;

namespace FS.TimeTracking.Repository.DbContexts
{
    /// <inheritdoc />
    public class TimeTrackingDbContext : DbContext
    {
        private readonly ILoggerFactory _loggerFactory;
        private readonly TimeTrackingConfiguration _configuration;
        private readonly EnvironmentConfiguration _environment;

        /// <summary>
        /// Initializes a new instance of the <see cref="TimeTrackingDbContext"/> class.
        /// </summary>
        /// <param name="loggerFactory">The logger factory.</param>
        /// <param name="configuration">The configuration.</param>
        /// <param name="environment">The environment.</param>
        /// <autogeneratedoc />
        public TimeTrackingDbContext(ILoggerFactory loggerFactory, TimeTrackingConfiguration configuration, EnvironmentConfiguration environment)
        {
            _loggerFactory = loggerFactory;
            _configuration = configuration;
            _environment = environment;
        }

        /// <inheritdoc />
        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            LinqToDBForEFTools.Initialize();

            options
                .UseLoggerFactory(_loggerFactory)
                .EnableSensitiveDataLogging(_environment.IsDevelopment);

            var connectionString = _configuration.Database.ConnectionString;
            var repositoryAssemblyName = typeof(TimeTrackingDbContext).Assembly.GetName().Name;
            var migrationAssembly = $"{repositoryAssemblyName}.{_configuration.Database.Type}";

            switch (_configuration.Database.Type)
            {
                case DatabaseType.SqLite:
                    options.UseSqlite(connectionString, o => o.MigrationsAssembly(migrationAssembly));
                    break;
                case DatabaseType.SqlServer:
                    options.UseSqlServer(connectionString, o => o.MigrationsAssembly(migrationAssembly));
                    break;
                case DatabaseType.PostgreSql:
                    options.UseNpgsql(connectionString, o => o.MigrationsAssembly(migrationAssembly));
                    break;
                case DatabaseType.MySql:
                    var serverVersion = ServerVersion.AutoDetect(connectionString);
                    options.UseMySql(connectionString, serverVersion, o => o.MigrationsAssembly(migrationAssembly));
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }

        /// <inheritdoc />
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            ConfigureCustomer(modelBuilder.Entity<Customer>());
            ConfigureProject(modelBuilder.Entity<Project>());
            ConfigureActivity(modelBuilder.Entity<Activity>());
            ConfigureTimeSheet(modelBuilder.Entity<TimeSheet>());
        }

        private static void ConfigureCustomer(EntityTypeBuilder<Customer> customerBuilder)
        {
            customerBuilder
                .ToTable("Customers")
                .HasIndex(customer => new { customer.ShortName, customer.Hidden });
        }

        private static void ConfigureProject(EntityTypeBuilder<Project> projectBuilder)
        {
            projectBuilder
                .ToTable("Projects")
                .HasIndex(project => new { project.Name, project.Hidden });

            projectBuilder
                .HasOne(project => project.Customer)
                .WithMany(customer => customer.Projects)
                .HasForeignKey(project => project.CustomerId)
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        }

        private static void ConfigureActivity(EntityTypeBuilder<Activity> activityBuilder)
        {
            activityBuilder
                .ToTable("Activities")
                .HasIndex(activity => new { activity.Name, activity.Hidden });

            activityBuilder
                .HasOne(activity => activity.Customer)
                .WithMany()
                .HasForeignKey(activity => activity.CustomerId)
                .OnDelete(DeleteBehavior.Restrict);

            activityBuilder
                .HasOne(activity => activity.Project)
                .WithMany()
                .HasForeignKey(activity => activity.ProjectId)
                .OnDelete(DeleteBehavior.Restrict);
        }

        private static void ConfigureTimeSheet(EntityTypeBuilder<TimeSheet> timeSheetBuilder)
        {
            timeSheetBuilder
                .ToTable("TimeSheets");

            timeSheetBuilder
                .HasOne<Customer>()
                .WithMany()
                .HasForeignKey(timeSheet => timeSheet.CustomerId)
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            timeSheetBuilder
                .HasOne<Activity>()
                .WithMany()
                .HasForeignKey(timeSheet => timeSheet.ActivityId)
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        }
    }
}
