using FS.TimeTracking.Shared.Interfaces.Application.Converters;
using FS.TimeTracking.Shared.Interfaces.Application.Services;
using FS.TimeTracking.Shared.Interfaces.Models;
using FS.TimeTracking.Shared.Interfaces.Services;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace FS.TimeTracking.Application.Services
{
    /// <inheritdoc />
    public abstract class CrudModelService<TModel, TDto> : ICrudModelService<TDto>
        where TModel : class, IEntityModel, new()
    {
        private readonly IRepository _repository;
        private readonly IModelConverter<TModel, TDto> _modelConverter;

        /// <summary>
        /// Initializes a new instance of the <see cref="CrudModelService{TModel, TDto}"/> class.
        /// </summary>
        /// <param name="repository">The repository.</param>
        /// <param name="modelConverter">The model converter.</param>
        /// <autogeneratedoc />
        protected CrudModelService(IRepository repository, IModelConverter<TModel, TDto> modelConverter)
        {
            _repository = repository;
            _modelConverter = modelConverter;
        }

        /// <inheritdoc />
        public async Task<List<TDto>> Query(CancellationToken cancellationToken = default)
            => await _repository
                .Get(
                    select: (TModel x) => _modelConverter.ToDto(x),
                    cancellationToken: cancellationToken
                );

        /// <inheritdoc />
        public async Task<TDto> Get(Guid id, CancellationToken cancellationToken = default)
            => await _repository
                .FirstOrDefault(
                    select: (TModel x) => _modelConverter.ToDto(x),
                    where: x => x.Id == id,
                    cancellationToken: cancellationToken
                );

        /// <inheritdoc />
        public async Task<TDto> Create(TDto dto)
        {
            var result = await _repository.Add(_modelConverter.FromDto(dto));
            await _repository.SaveChanges();
            return _modelConverter.ToDto(result);
        }

        /// <inheritdoc />
        public async Task<TDto> Update(TDto dto)
        {
            var result = _repository.Update(_modelConverter.FromDto(dto));
            await _repository.SaveChanges();
            return _modelConverter.ToDto(result);
        }

        /// <inheritdoc />
        public async Task<long> Delete(Guid id)
        {
            await _repository.Remove<TModel>(x => x.Id == id);
            return await _repository.SaveChanges();
        }
    }
}