#if DEBUG
using FS.TimeTracking.Shared.Interfaces.Application.Services;
using FS.TimeTracking.Shared.Interfaces.Services;
using FS.TimeTracking.Shared.Models.TimeTracking;
using System.Threading;
using System.Threading.Tasks;

namespace FS.TimeTracking.Application.Services
{
    /// <inheritdoc />
    public class DebugService : IDebugService
    {
        private readonly IRepository _repository;

        /// <summary>
        /// Initializes a new instance of the <see cref="DebugService"/> class.
        /// </summary>
        /// <param name="repository">The repository.</param>
        /// <autogeneratedoc />
        public DebugService(IRepository repository)
            => _repository = repository;

        /// <inheritdoc />
        public async Task<object> TestMethod(CancellationToken cancellationToken = default)
        {
            await _repository.Add(new Customer { Title = "Test" }, cancellationToken);
            await _repository.SaveChanges(cancellationToken);
            var customer = await _repository.FirstOrDefault((Customer x) => x, cancellationToken: cancellationToken);
            return Task.FromResult<object>(1);
        }
    }
}
#endif