/*
 * Time Tracking Report API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FS.TimeTracking.Report.Client.Api;
using FS.TimeTracking.Report.Client.Model;
using FS.TimeTracking.Report.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FS.TimeTracking.Report.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ActivityReportTimeSheetDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActivityReportTimeSheetDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ActivityReportTimeSheetDto
        //private ActivityReportTimeSheetDto instance;

        public ActivityReportTimeSheetDtoTests()
        {
            // TODO uncomment below to create an instance of ActivityReportTimeSheetDto
            //instance = new ActivityReportTimeSheetDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActivityReportTimeSheetDto
        /// </summary>
        [Fact]
        public void ActivityReportTimeSheetDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ActivityReportTimeSheetDto
            //Assert.IsType<ActivityReportTimeSheetDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Fact]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'Issue'
        /// </summary>
        [Fact]
        public void IssueTest()
        {
            // TODO unit test for the property 'Issue'
        }
        /// <summary>
        /// Test the property 'CustomerTitle'
        /// </summary>
        [Fact]
        public void CustomerTitleTest()
        {
            // TODO unit test for the property 'CustomerTitle'
        }
        /// <summary>
        /// Test the property 'ProjectTitle'
        /// </summary>
        [Fact]
        public void ProjectTitleTest()
        {
            // TODO unit test for the property 'ProjectTitle'
        }
        /// <summary>
        /// Test the property 'ActivityTitle'
        /// </summary>
        [Fact]
        public void ActivityTitleTest()
        {
            // TODO unit test for the property 'ActivityTitle'
        }
        /// <summary>
        /// Test the property 'OrderTitle'
        /// </summary>
        [Fact]
        public void OrderTitleTest()
        {
            // TODO unit test for the property 'OrderTitle'
        }
        /// <summary>
        /// Test the property 'OrderNumber'
        /// </summary>
        [Fact]
        public void OrderNumberTest()
        {
            // TODO unit test for the property 'OrderNumber'
        }
        /// <summary>
        /// Test the property 'Billable'
        /// </summary>
        [Fact]
        public void BillableTest()
        {
            // TODO unit test for the property 'Billable'
        }
        /// <summary>
        /// Test the property 'CustomerCompanyName'
        /// </summary>
        [Fact]
        public void CustomerCompanyNameTest()
        {
            // TODO unit test for the property 'CustomerCompanyName'
        }
        /// <summary>
        /// Test the property 'CustomerDepartment'
        /// </summary>
        [Fact]
        public void CustomerDepartmentTest()
        {
            // TODO unit test for the property 'CustomerDepartment'
        }
        /// <summary>
        /// Test the property 'CustomerContactName'
        /// </summary>
        [Fact]
        public void CustomerContactNameTest()
        {
            // TODO unit test for the property 'CustomerContactName'
        }
        /// <summary>
        /// Test the property 'GroupBy'
        /// </summary>
        [Fact]
        public void GroupByTest()
        {
            // TODO unit test for the property 'GroupBy'
        }

    }

}
