/*
 * Time Tracking Report API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FS.TimeTracking.Report.Client.Api;
using FS.TimeTracking.Report.Client.Model;
using FS.TimeTracking.Report.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FS.TimeTracking.Report.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ProductInformationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductInformationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductInformationDto
        //private ProductInformationDto instance;

        public ProductInformationDtoTests()
        {
            // TODO uncomment below to create an instance of ProductInformationDto
            //instance = new ProductInformationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductInformationDto
        /// </summary>
        [Fact]
        public void ProductInformationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductInformationDto
            //Assert.IsType<ProductInformationDto>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'Copyright'
        /// </summary>
        [Fact]
        public void CopyrightTest()
        {
            // TODO unit test for the property 'Copyright'
        }

    }

}
