using FS.FilterExpressionCreator.Filters;
using FS.TimeTracking.Abstractions.DTOs.MasterData;
using FS.TimeTracking.Abstractions.DTOs.TimeTracking;
using FS.TimeTracking.Application.AutoMapper;
using FS.TimeTracking.Core.Extensions;
using FS.TimeTracking.Core.Interfaces.Application.Services.MasterData;
using FS.TimeTracking.Core.Interfaces.Application.Services.Report;
using FS.TimeTracking.Core.Interfaces.Repository.Services;
using FS.TimeTracking.Core.Models.Application.TimeTracking;
using FS.TimeTracking.Report.Abstractions.DTOs.Reports;
using FS.TimeTracking.Report.Abstractions.Enums.Report;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace FS.TimeTracking.Application.Services.Report;

/// <inheritdoc />
public class ActivityReportService : IActivityReportService
{
    private readonly ISettingService _settingService;
    private readonly IRepository _repository;

    /// <summary>
    /// Initializes a new instance of the <see cref="ActivityReportService"/> class.
    /// </summary>
    /// <param name="settingService">The setting service.</param>
    /// <param name="repository">The repository.</param>
    /// <autogeneratedoc />
    public ActivityReportService(ISettingService settingService, IRepository repository)
    {
        _settingService = settingService;
        _repository = repository;
    }

    /// <inheritdoc />
    public async Task<ActivityReportDto> GetDetailedActivityReport(EntityFilter<TimeSheetDto> timeSheetFilter, EntityFilter<ProjectDto> projectFilter, EntityFilter<CustomerDto> customerFilter, EntityFilter<ActivityDto> activityFilter, EntityFilter<OrderDto> orderFilter, EntityFilter<HolidayDto> holidayFilter, string language, ActivityReportGroup groupBy, CancellationToken cancellationToken = default)
    {
        var data = await GetActivityReportData(timeSheetFilter, projectFilter, customerFilter, activityFilter, orderFilter, holidayFilter, language, groupBy, cancellationToken);
        return data;
    }

    /// <inheritdoc />
    public async Task<ActivityReportDto> GetDetailedActivityReportPreview(EntityFilter<TimeSheetDto> timeSheetFilter, EntityFilter<ProjectDto> projectFilter, EntityFilter<CustomerDto> customerFilter, EntityFilter<ActivityDto> activityFilter, EntityFilter<OrderDto> orderFilter, EntityFilter<HolidayDto> holidayFilter, string language, ActivityReportGroup groupBy, CancellationToken cancellationToken = default)
    {
        return await GetActivityReportData(timeSheetFilter, projectFilter, customerFilter, activityFilter, orderFilter, holidayFilter, language, groupBy, cancellationToken);
    }

    /// <inheritdoc />
    public async Task<ActivityReportDto> GetActivityReportData(EntityFilter<TimeSheetDto> timeSheetFilter, EntityFilter<ProjectDto> projectFilter, EntityFilter<CustomerDto> customerFilter, EntityFilter<ActivityDto> activityFilter, EntityFilter<OrderDto> orderFilter, EntityFilter<HolidayDto> holidayFilter, string language, ActivityReportGroup groupBy, CancellationToken cancellationToken = default)
    {
        var selectedPeriod = FilterExtensions.GetSelectedPeriod(timeSheetFilter);
        var parameters = new ReportParameter { StartDate = selectedPeriod.Start, EndDate = selectedPeriod.End };

        var provider = await GetProviderInformation(cancellationToken);

        var translations = await _settingService.GetTranslations(language, cancellationToken);
        var reportTranslations = translations
            .SelectToken("Page.Report.Activity")
            .ToDictionary()
            .ToDictionary(x => x.Key, x => x.Value.Trim('"'));

        var timeSheets = await GetTimeSheets(timeSheetFilter, projectFilter, customerFilter, activityFilter, orderFilter, holidayFilter, cancellationToken);
        SetGroupByMember(timeSheets, groupBy, reportTranslations);

        return new ActivityReportDto
        {
            Parameters = parameters,
            Provider = provider,
            Translations = reportTranslations,
            TimeSheets = timeSheets,
        };
    }

    private async Task<ProviderDto> GetProviderInformation(CancellationToken cancellationToken)
    {
        var settings = await _settingService.GetSettings(cancellationToken);
        var provider = new ProviderDto
        {
            Name = settings.Company.Provider,
            Company = settings.Company.Company,
            Department = settings.Company.Department,
        };
        return provider;
    }

    private async Task<List<ActivityReportTimeSheetDto>> GetTimeSheets(EntityFilter<TimeSheetDto> timeSheetFilter, EntityFilter<ProjectDto> projectFilter, EntityFilter<CustomerDto> customerFilter, EntityFilter<ActivityDto> activityFilter, EntityFilter<OrderDto> orderFilter, EntityFilter<HolidayDto> holidayFilter, CancellationToken cancellationToken = default)
    {
        var filter = FilterExtensions.CreateTimeSheetFilter(timeSheetFilter, projectFilter, customerFilter, activityFilter, orderFilter, holidayFilter);

        var timeSheets = await _repository
            .Get<TimeSheet, ActivityReportTimeSheetDto>(
                where: filter,
                orderBy: o => o.OrderBy(x => x.StartDateLocal),
                cancellationToken: cancellationToken
            );

        return timeSheets;
    }

    private static void SetGroupByMember(List<ActivityReportTimeSheetDto> timeSheets, ActivityReportGroup groupBy, Dictionary<string, string> reportTranslations)
    {
        reportTranslations.Add("GroupByTitle", reportTranslations.FirstOrDefault(x => x.Key == groupBy.ToString()).Value);
        foreach (var timeSheet in timeSheets)
            timeSheet.GroupBy = groupBy switch
            {
                ActivityReportGroup.None => null,
                ActivityReportGroup.Issue => timeSheet.Issue,
                ActivityReportGroup.OrderNumber => timeSheet.OrderNumber,
                _ => throw new ArgumentOutOfRangeException(nameof(groupBy), groupBy, null)
            };
    }
}