using FS.TimeTracking.Shared.Models.Application.MasterData;
using FS.TimeTracking.Shared.Models.Application.TimeTracking;
using System.ComponentModel.DataAnnotations;

namespace FS.TimeTracking.Shared.Models.Application.Report;

/// <summary>
/// Work times per project.
/// </summary>
/// <autogeneratedoc />
internal class IssueWorkTime : WorkTime
{
    /// <inheritdoc cref="TimeSheet.Issue"/>
    [Required]
    public string Issue { get; set; }

    /// <inheritdoc cref="Customer.Title"/>
    [Required]
    public string CustomerTitle { get; set; }
}