using System;
using System.ComponentModel.DataAnnotations;
using FS.TimeTracking.Shared.DTOs.Report;
using FS.TimeTracking.Shared.Models.Application.MasterData;

namespace FS.TimeTracking.Shared.Models.Application.Report;

/// <summary>
/// Work times.
/// </summary>
/// <autogeneratedoc />
public abstract class WorkTime
{
    /// <inheritdoc cref="WorkTimeDto.TimeWorked"/>
    [Required]
    public TimeSpan WorkedTime { get; set; }

    /// <inheritdoc cref="WorkTimeDto.DaysWorked"/>
    [Required]
    public double WorkedDays { get; set; }

    /// <inheritdoc cref="WorkTimeDto.BudgetWorked"/>
    [Required]
    public double WorkedBudget => WorkedTime.TotalHours * HourlyRate;

    /// <inheritdoc cref="WorkTimeDto.TimePlanned"/>
    [Required]
    public TimeSpan PlannedTime { get; set; }

    /// <inheritdoc cref="WorkTimeDto.DaysPlanned"/>
    [Required]
    public double PlannedDays { get; set; }

    /// <inheritdoc cref="WorkTimeDto.BudgetPlanned"/>
    [Required]
    public double PlannedBudget => PlannedTime.TotalHours * HourlyRate;

    /// <inheritdoc cref="Order.HourlyRate"/>
    [Required]
    public double HourlyRate { get; set; }

    /// <inheritdoc cref="Order.StartDate"/>
    [Required]
    public DateTimeOffset PlannedStart { get; set; }

    /// <inheritdoc cref="Order.DueDate"/>
    [Required]
    public DateTimeOffset PlannedEnd { get; set; }
}