using System.Collections.Generic;
using System.Linq;

namespace FS.TimeTracking.Abstractions.Constants;

internal class PermissionName
{
    /// <summary>
    /// Permission for data of other users.
    /// </summary>
    public const string FOREIGN_DATA = "foreign-data";

    /// <summary>
    /// Permission for time sheets.
    /// </summary>
    public const string TIME_SHEET = "time-sheet";

    /// <summary>
    /// Permission for charts by customer.
    /// </summary>
    public const string CHARTS_BY_CUSTOMER = "charts-by-customer";

    /// <summary>
    /// Permission for charts by order.
    /// </summary>
    public const string CHARTS_BY_ORDER = "charts-by-order";

    /// <summary>
    /// Permission for charts by project.
    /// </summary>
    public const string CHARTS_BY_PROJECT = "charts-by-project";

    /// <summary>
    /// Permission for charts by activity.
    /// </summary>
    public const string CHARTS_BY_ACTIVITY = "charts-by-activity";

    /// <summary>
    /// Permission for charts by issue.
    /// </summary>
    public const string CHARTS_BY_ISSUE = "charts-by-issue";

    /// <summary>
    /// Permission for summary activity report.
    /// </summary>
    public const string REPORT_ACTIVITY_SUMMARY = "report-activity-summary";

    /// <summary>
    /// Permission for detailed activity report.
    /// </summary>
    public const string REPORT_ACTIVITY_DETAIL = "report-activity-detail";

    /// <summary>
    /// Permission for activity report raw data.
    /// </summary>
    public const string REPORT_ACTIVITY_RAW_DATA = "report-activity-raw-data";

    /// <summary>
    /// Permission for master data customers.
    /// </summary>
    public const string MASTER_DATA_CUSTOMERS = "master-data-customers";

    /// <summary>
    /// Permission for master data projects.
    /// </summary>
    public const string MASTER_DATA_PROJECTS = "master-data-projects";

    /// <summary>
    /// Permission for master data activities.
    /// </summary>
    public const string MASTER_DATA_ACTIVITIES = "master-data-activities";

    /// <summary>
    /// Permission for master data orders.
    /// </summary>
    public const string MASTER_DATA_ORDERS = "master-data-orders";

    /// <summary>
    /// Permission for master data holidays.
    /// </summary>
    public const string MASTER_DATA_HOLIDAYS = "master-data-holidays";

    /// <summary>
    /// Permission for users administration.
    /// </summary>
    public const string ADMINISTRATION_USERS = "administration-users";

    /// <summary>
    /// Permission for administrative settings.
    /// </summary>
    public const string ADMINISTRATION_SETTINGS = "administration-settings";

    /// <summary>
    /// All role names.
    /// </summary>
    public static IEnumerable<string> All { get; } = GetAllPermissionNames();

    /// <summary>
    /// Permissions used to build policies for generic CRUD model services.
    /// </summary>
    /// <autogeneratedoc />
    public static string[] CrudServicePermissionNames { get; } = {
        MASTER_DATA_CUSTOMERS,
        MASTER_DATA_PROJECTS,
        MASTER_DATA_ACTIVITIES,
        MASTER_DATA_ORDERS,
        MASTER_DATA_HOLIDAYS,
        ADMINISTRATION_USERS,
    };

    private static IEnumerable<string> GetAllPermissionNames()
        => typeof(RoleName)
            .GetFields()
            .Where(x => x.IsLiteral)
            .Select(x => (string)x.GetValue(null))
            .ToList();
}