namespace FS.TimeTracking.Abstractions.Constants;

/// <summary>
/// Restrict to customer attribute / scope / mapper names.
/// </summary>
/// <autogeneratedoc />
public static class RestrictToCustomer
{
    /// <summary>
    /// Name of the (user) attribute to hold restricted customer IDs.
    /// </summary>
    public const string ATTRIBUTE = "restrict_to_customer_id";

    /// <summary>
    /// Name of the client scope to map user's 'restricted customer IDs' to JWT.
    /// </summary>
    public const string CLIENT_SCOPE = ATTRIBUTE;

    /// <summary>
    /// Name of the mapper to map user's 'restricted customer IDs' to JWT.
    /// </summary>
    public const string MAPPER = ATTRIBUTE;

    /// <summary>
    /// Name of claim holding the customer IDs the user is restricted to.
    /// </summary>
    public const string CLAIM = ATTRIBUTE;
}