using System.Diagnostics.CodeAnalysis;

namespace FS.TimeTracking.Abstractions.DTOs.Shared;

/// <summary>
/// Non-generic factory for <see cref="TypeaheadDto{TKey, TValue}"/>.
/// </summary>
[ExcludeFromCodeCoverage]
public record TypeaheadDto
{
    /// <summary>
    /// Initializes a new instance of the <see cref="TypeaheadDto{TKey, TValue}"/> class.
    /// </summary>
    /// <typeparam name="TKey">The type of the key.</typeparam>
    /// <typeparam name="TValue">The type of the value.</typeparam>
    /// <param name="id">The value to be selected.</param>
    /// <param name="value">The label to display.</param>
    /// <param name="hidden"><c>true</c>, if the value is hidden; otherwise false.</param>
    public static TypeaheadDto<TKey, TValue> Create<TKey, TValue>(TKey id, TValue value, bool hidden = false)
        => new(id, value, hidden);
}

/// <summary>
/// Generic type ahead DTO.
/// </summary>
/// <typeparam name="TKey">The type of the key.</typeparam>
/// <typeparam name="TValue">The type of the value.</typeparam>
[ExcludeFromCodeCoverage]
public record TypeaheadDto<TKey, TValue>
{
    /// <summary>
    /// The ID of the entity.
    /// </summary>
    public TKey Id { get; set; }

    /// <summary>
    /// The label to display.
    /// </summary>
    public TValue Value { get; set; }

    /// <summary>
    /// Indicates whether the entity is marked as hidden.
    /// </summary>
    public bool Hidden { get; set; }

    /// <summary>
    /// Extended properties, e.g. related customer to an order.
    /// </summary>
    public object Extended { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="TypeaheadDto{TKey, TValue}"/> class.
    /// </summary>
    /// <autogeneratedoc />
    public TypeaheadDto() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="TypeaheadDto{TKey, TValue}" /> class.
    /// </summary>
    /// <param name="id">The value to be selected.</param>
    /// <param name="value">The label to display.</param>
    /// <param name="hidden"><c>true</c>, if the value is hidden; otherwise false.</param>
    public TypeaheadDto(TKey id, TValue value, bool hidden)
        => (Id, Value, Hidden) = (id, value, hidden);
}