using System;

namespace FS.TimeTracking.Core.Interfaces.Models;

/// <summary>
/// Interface for user related models.
/// </summary>
/// <autogeneratedoc />
public interface IUserRelatedModel
{
    /// <summary>
    /// The unique identifier of the user.
    /// </summary>
    Guid UserId { get; set; }
}