using AutoMapper;
using FS.TimeTracking.Abstractions.DTOs.MasterData;
using FS.TimeTracking.Application.Services.Shared;
using FS.TimeTracking.Core.Interfaces.Application.Services.Administration;
using FS.TimeTracking.Core.Interfaces.Application.Services.MasterData;
using FS.TimeTracking.Core.Interfaces.Application.Services.Shared;
using FS.TimeTracking.Core.Interfaces.Repository.Services.Database;
using FS.TimeTracking.Core.Models.Application.MasterData;
using FS.TimeTracking.Core.Models.Filter;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace FS.TimeTracking.Application.Services.MasterData;

/// <inheritdoc cref="ICustomerApiService" />
public class CustomerService : CrudModelService<Customer, CustomerDto, CustomerGridDto>, ICustomerApiService
{
    /// <summary>
    /// Initializes a new instance of the <see cref="CustomerService"/> class.
    /// </summary>
    /// <param name="authorizationService">The authorization service.</param>
    /// <param name="dbRepository">The database repository.</param>
    /// <param name="mapper">The mapper.</param>
    /// <param name="filterFactory">The filter factory.</param>
    /// <param name="userService">The user service.</param>
    /// <autogeneratedoc />
    public CustomerService(IAuthorizationService authorizationService, IDbRepository dbRepository, IMapper mapper, IFilterFactory filterFactory, IUserService userService)
        : base(authorizationService, dbRepository, mapper, filterFactory, userService)
    { }

    /// <inheritdoc />
    public override async Task<List<CustomerGridDto>> GetGridFiltered(TimeSheetFilterSet filters, CancellationToken cancellationToken = default)
    {
        var filter = await FilterFactory.CreateCustomerFilter(filters);

        var gridItems = await DbRepository
            .Get<Customer, CustomerGridDto>(
                where: filter,
                orderBy: o => o
                    .OrderBy(x => x.Hidden)
                    .ThenBy(x => x.Title)
                    .ThenBy(x => x.CompanyName)
                    .ThenBy(x => x.ContactName),
                cancellationToken: cancellationToken
            );

        await AuthorizationService.SetAuthorizationRelatedProperties(gridItems, cancellationToken);

        return gridItems;
    }
}