using System;

namespace FS.TimeTracking.Shared.Extensions
{
    /// <summary>
    /// Extensions methods for type <see cref="DateTime"></see>
    /// </summary>
    /// <autogeneratedoc />
    public static class DateTimeExtensions
    {
        /// <summary>
        /// Converts a <see cref="DateTime"/> to a <see cref="DateTimeOffset"/> using a given offset.
        /// </summary>
        /// <param name="dateTime">The date time.</param>
        /// <param name="offset">The offset to use.</param>
        public static DateTimeOffset ToOffset(this DateTime dateTime, TimeSpan? offset)
        {
            if (dateTime.Kind == DateTimeKind.Unspecified)
                throw new ArgumentException($"The kind must not be '{nameof(DateTimeKind.Unspecified)}'", nameof(dateTime));
            return new DateTimeOffset(dateTime.ToUniversalTime(), TimeSpan.Zero).ToOffset(offset ?? TimeSpan.Zero);
        }

        /// <summary>
        /// Converts a <see cref="DateTime"/> to a <see cref="DateTimeOffset"/> using a given offset.
        /// </summary>
        /// <param name="dateTime">The date time.</param>
        /// <param name="offset">The offset to use.</param>
        public static DateTimeOffset? ToOffset(this DateTime? dateTime, TimeSpan? offset)
            => dateTime?.ToOffset(offset);
    }
}
