using FS.TimeTracking.Abstractions.DTOs.Administration;
using System;

namespace FS.TimeTracking.Abstractions.Interfaces.DTOs;

/// <summary>
/// Interface for user related grid DTOs.
/// </summary>
/// <autogeneratedoc />
public interface IUserRelatedGridDto
{
    /// <inheritdoc cref="UserDto.Id"/>
    Guid UserId { get; set; }

    /// <inheritdoc cref="UserDto.Username"/>
    string Username { get; set; }
}