using FS.TimeTracking.Shared.Extensions;
using System;
using System.IO;

namespace FS.TimeTracking.Report.Abstractions.Models.Configuration;

/// <summary>
/// Global application configuration
/// </summary>
public class TimeTrackingReportConfiguration
{
    /// <summary>
    /// The configuration section bind to.
    /// </summary>
    internal const string CONFIGURATION_SECTION = "TimeTrackingReport";

    /// <summary>
    /// Pathname of the configuration folder.
    /// </summary>
    internal const string CONFIG_FOLDER = "config";

    /// <summary>
    /// Name of the configuration file.
    /// </summary>
    /// <autogeneratedoc />
    internal const string CONFIG_BASE_NAME = "FS.TimeTracking.Report.config";

    /// <summary>
    /// The nlog configuration file.
    /// </summary>
    /// <autogeneratedoc />
    internal const string NLOG_CONFIGURATION_FILE = CONFIG_BASE_NAME + ".nlog";

    /// <summary>
    /// Full pathname of the executable file.
    /// </summary>
    /// <autogeneratedoc />
    internal static readonly string ExecutablePath = AssemblyExtensions.GetProgramDirectory();

    /// <summary>
    /// Pathname of folder containing reporting files.
    /// </summary>
    internal const string REPORT_FOLDER = "Reports";

    /// <summary>
    /// Path to the content root.
    /// </summary>
    /// <autogeneratedoc />
    internal static readonly string PathToContentRoot = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Development"
        ? Directory.GetCurrentDirectory()
        : ExecutablePath;

    /// <summary>
    /// Gets or sets the license key for Stimulsoft reports.
    /// </summary>
    public string StimulsoftLicenseKey { get; set; }
}