using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FS.TimeTracking.Tool.Models.Imports;

/// <summary>
/// Customer
/// </summary>
public class KimaiV1Customer
{
    /// <summary>
    /// Gets the unique identifier for <see cref="Customer.Id"/>.
    /// </summary>
    /// <autogeneratedoc />
    [NotMapped]
    public Guid Id { get; } = Guid.NewGuid();

    /// <summary>
    /// Gets the unique identifier.
    /// </summary>
    [Required]
    public int CustomerId { get; set; }

    /// <summary>
    /// Gets or sets the short/display name.
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    /// <summary>
    /// Gets or sets the name of the company.
    /// </summary>
    [StringLength(100)]
    public string Company { get; set; }

    /// <summary>
    /// Gets or sets the name of the contact.
    /// </summary>
    [StringLength(100)]
    public string Contact { get; set; }

    /// <summary>
    /// Gets or sets the street.
    /// </summary>
    [StringLength(100)]
    public string Street { get; set; }

    /// <summary>
    /// Gets or sets the zip code.
    /// </summary>
    [StringLength(100)]
    public string ZipCode { get; set; }

    /// <summary>
    /// Gets or sets the city.
    /// </summary>
    [StringLength(100)]
    public string City { get; set; }

    /// <summary>
    /// Gets or sets the country.
    /// </summary>
    [StringLength(100)]
    public string Country { get; set; }

    /// <summary>
    /// Gets or sets a comment.
    /// </summary>
    public string Comment { get; set; }

    /// <summary>
    /// Gets or sets the timezone for the customer.
    /// </summary>
    public string TimeZone { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this item is hidden.
    /// </summary>
    [Required]
    public bool Visible { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this item is hidden.
    /// </summary>
    [Required]
    public bool Trash { get; set; }
}