using FS.TimeTracking.Core.Models.Application.Core;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace FS.TimeTracking.Core.Exceptions;

/// <summary>
/// Base class for signalling application specific errors having an error code and message.
/// </summary>
public abstract class ApplicationErrorException : Exception
{
    /// <summary>
    /// Error code of conformity violation.
    /// </summary>
    public ApplicationErrorCode? ErrorCode { get; }

    /// <summary>
    /// Detailed causes for the conformity violation.
    /// </summary>
    public IEnumerable<string> Errors { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="ConformityException"/> class.
    /// </summary>
    /// <param name="errorCode">The error code.</param>
    /// <param name="errors">A variable-length parameters list containing errors.</param>
    /// <autogeneratedoc />
    protected ApplicationErrorException(ApplicationErrorCode errorCode, params string[] errors)
        : base(GetExceptionMessage(errors))
    {
        ErrorCode = errorCode;
        Errors = errors;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="ConformityException"/> class.
    /// </summary>
    /// <param name="errors">A variable-length parameters list containing errors.</param>
    protected ApplicationErrorException(params string[] errors)
        : base(GetExceptionMessage(errors))
        => Errors = errors;

    /// <summary>
    /// Initializes a new instance of the <see cref="ConformityException"/> class.
    /// </summary>
    /// <param name="errors">A variable-length parameters list containing errors.</param>
    [SuppressMessage("ReSharper", "PossibleMultipleEnumeration", Justification = "Unable to resolve in code")]
    protected ApplicationErrorException(IEnumerable<string> errors)
        : base(GetExceptionMessage(errors))
        => Errors = errors;

    private static string GetExceptionMessage(IEnumerable<string> errors)
        => string.Join(", ", errors);
}