/*
 * Time Tracking Report API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using FS.TimeTracking.Report.Client.Client;
using FS.TimeTracking.Report.Client.Api;
// uncomment below to import models
//using FS.TimeTracking.Report.Client.Model;

namespace FS.TimeTracking.Report.Client.Test.Api
{
    /// <summary>
    ///  Class for testing ActivityReportApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ActivityReportApiTests : IDisposable
    {
        private ActivityReportApi instance;

        public ActivityReportApiTests()
        {
            instance = new ActivityReportApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActivityReportApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ActivityReportApi
            //Assert.IsType<ActivityReportApi>(instance);
        }

        /// <summary>
        /// Test ActivityReportGenerateActivityReport
        /// </summary>
        [Fact]
        public void ActivityReportGenerateActivityReportTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ActivityReportDto? activityReportDto = null;
            //instance.ActivityReportGenerateActivityReport(activityReportDto);
        }

        /// <summary>
        /// Test ActivityReportGenerateActivityReportPreview
        /// </summary>
        [Fact]
        public void ActivityReportGenerateActivityReportPreviewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ActivityReportDto? activityReportDto = null;
            //instance.ActivityReportGenerateActivityReportPreview(activityReportDto);
        }
    }
}
