/*
 * Time Tracking Report API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using FS.TimeTracking.Report.Client.Client;
using FS.TimeTracking.Report.Client.Api;
// uncomment below to import models
//using FS.TimeTracking.Report.Client.Model;

namespace FS.TimeTracking.Report.Client.Test.Api
{
    /// <summary>
    ///  Class for testing InformationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class InformationApiTests : IDisposable
    {
        private InformationApi instance;

        public InformationApiTests()
        {
            instance = new InformationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InformationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' InformationApi
            //Assert.IsType<InformationApi>(instance);
        }

        /// <summary>
        /// Test InformationGetProductCopyright
        /// </summary>
        [Fact]
        public void InformationGetProductCopyrightTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.InformationGetProductCopyright();
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test InformationGetProductInformation
        /// </summary>
        [Fact]
        public void InformationGetProductInformationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.InformationGetProductInformation();
            //Assert.IsType<ProductInformationDto>(response);
        }

        /// <summary>
        /// Test InformationGetProductName
        /// </summary>
        [Fact]
        public void InformationGetProductNameTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.InformationGetProductName();
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test InformationGetProductVersion
        /// </summary>
        [Fact]
        public void InformationGetProductVersionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.InformationGetProductVersion();
            //Assert.IsType<string>(response);
        }
    }
}
