using AutoMapper;
using FS.TimeTracking.Shared.DTOs.TimeTracking;
using FS.TimeTracking.Shared.Models.TimeTracking;

namespace FS.TimeTracking.Application.AutoMapper
{
    /// <summary>
    /// Configuration profile for auto mapper.
    /// </summary>
    /// <seealso cref="Profile" />
    public class TimeTrackingProfile : Profile
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TimeTrackingProfile"/> class.
        /// </summary>
        /// <autogeneratedoc />
        public TimeTrackingProfile()
        {
            ClearPrefixes();

            CreateMap<Customer, CustomerDto>()
                .ReverseMap();

            CreateMap<Project, ProjectDto>()
                .ReverseMap();

            CreateMap<Activity, ActivityDto>()
                .ReverseMap();

            CreateMap<TimeSheet, TimeSheetDto>()
                .ReverseMap()
                .ForMember(x => x.StartDateOffset, o => o.Ignore())
                .ForMember(x => x.EndDateOffset, o => o.Ignore());

            CreateMap<Project, ProjectListDto>();
            CreateMap<Activity, ActivityListDto>();
        }
    }
}
