using System.Diagnostics.CodeAnalysis;

namespace FS.TimeTracking.Api.REST.Routing;

/// <summary>
/// Feature modules flags.
/// </summary>
/// <autogeneratedoc />
[SuppressMessage("ReSharper", "InconsistentNaming")]
[ExcludeFromCodeCoverage]
public static class Features
{
    /// <summary>
    /// Gets or sets if the reporting module is enabled.
    /// </summary>
    public const string Reporting = nameof(Reporting);
}