[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("FS.TimeTracking")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("FS.TimeTracking.Abstractions.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("FS.TimeTracking.Application.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("FS.TimeTracking.Api.REST")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("FS.TimeTracking.Application")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("FS.TimeTracking.Repository")]